A test has been added to verify that the realm record in the krb5.conf configuration file matches one of the domain names in the resolv.conf configuration file.

diff --git a/diag-domain-controller b/diag-domain-controller
--- a/diag-domain-controller
+++ b/diag-domain-controller
@@ -421,6 +421,53 @@ is_resolv_conf_file_exists() {
     return $retval
 }
 
+# Checking whether the realm record in the krb5.conf configuration file matches one of the domain names in the resolv.conf configuration file
+does_resolv_conf_and_default_realm_it_match() {
+    local retval=2
+    local search_line=
+    local search_domains=
+    local krb5_default_realm_line=
+    local krb5_default_realm=
+    local domains=
+    local realm=
+
+    if test -e /etc/resolv.conf; then
+        search_line="$(grep "^search\s\+" /etc/resolv.conf || true)"
+        search_domains="$(echo "$search_line" | sed -e 's/^search\s\+//' -e 's/\s\+$//')"
+        domains=$(echo "$search_domains=" | tr '[:upper:]' '[:lower:]')
+
+        echo "The following domain names are defined from the \"resolv.conf\" configuration file:"
+        echo -e "$search_domains\n"
+    else
+        echo "The \"resolv.conf\" configuration file was not found."
+        retval=1
+    fi
+
+    if test -e /etc/krb5.conf; then
+        krb5_default_realm_line="$(grep "^\s*default_realm\s\+" /etc/krb5.conf || true)"
+        krb5_default_realm="$(echo "$krb5_default_realm_line" | sed -e 's/^\s*default_realm\s*=\s*//' -e 's/\s*$//')"
+        realm=$(echo "$krb5_default_realm=" | tr '[:upper:]' '[:lower:]')
+
+        echo "The following realm entry has been defined from the \"krb5.conf\" configuration file:"
+        echo -e "$krb5_default_realm\n"
+    else
+        echo -e "The \"krb5.conf\" configuration file was not found.\n"
+        retval=1
+    fi
+
+    for domain in $domains; do
+        test "$domain" = "$realm" && retval=0
+    done
+
+    if test "$retval" = 0; then
+        echo "The realm entry from the \"krb5.conf\" file matches the domain name defined in the \"resolv.conf\" file."
+    elif test "$retval" = 2; then
+        echo "The realm entry from the \"krb5.conf\" file does not match any of the domain name entries in the \"resolv.conf\" file."
+    fi
+
+    return $retval
+}
+
 # Samba databases are checked for errors
 are_there_errors_in_samba_databases() {
     local retval=0
@@ -487,6 +534,7 @@ task is_smb_conf_file_exists
 task is_there_way_to_cache_kerberos_tickets
 task is_dns_lookup_kdc_enabled
 task is_resolv_conf_file_exists
+task does_resolv_conf_and_default_realm_it_match
 task are_there_errors_in_samba_databases
 task is_ntp_service_running
 task is_time_synchronization_enabled
